sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: moveit/depth/cloud_filt
  max_range: 10.0
  max_update_rate: 1.0
  padding_offset: 0.0
  padding_scale: 0.0
  point_cloud_topic: moveit/depth/cloud_raw
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater